base_url = "https://ipetkov.github.io"
build_search_index = false
default_language = "en"
compile_sass = true
minify_html = true
feed_filename = "atom.xml"
generate_feed = true
taxonomies = [
    {name = 'tags'}
]
title = "Ivan Petkov"
theme = "terminimal"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"
external_links_no_follow = true
external_links_no_referrer = true

[extra]
accent_color = "green"
author = "Ivan Petkov"
enable_post_view_navigation = true
favicon = "/favicon.png"
favicon_mimetype = "image/png"
menu_items = [
    {name = "home", url = "$BASE_URL"},
    {name = "about", url = "$BASE_URL/about"},
    {name = "blog", url = "$BASE_URL/blog"},
    {name = "tags", url = "$BASE_URL/tags"},
]
post_view_navigation_prompt = ""
use_full_hack_font = false
