name: "pages"
on:
  push:
    branches:
      - "master"
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - name: zola build
        run: |
          mkdir output
          nix build --out-link result --print-build-logs
          rsync -r -L ./result/ ./output
      - name: setup SSH keys
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"
      - name: push
        working-directory: output
        run: |
          git init
          git config user.name "GitHub Actions"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git branch -M gh-pages
          git add .
          git commit -m "Deploying site"
          git push --force "git@github.com:${GITHUB_REPOSITORY}.git" gh-pages
